<?php
/**
 * corporate-munk Portfolio Post Type
 *
 * @package business-munk
 */

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function project_details_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function project_details_add_meta_box() {
	add_meta_box(
		'project_details-project-details',
		__( 'Project Details', 'project_details' ),
		'project_details_html',
		'mu_portfolio',
		'normal',
		'high'
	);
}
add_action( 'add_meta_boxes', 'project_details_add_meta_box' );

function project_details_html( $post) {
	wp_nonce_field( '_project_details_nonce', 'project_details_nonce' ); ?>

	<p>Portfolio Project Details</p>

	<p>
		<label for="project_details_client_name"><?php _e( 'Client Name', 'project_details' ); ?></label><br>
		<input type="text" name="project_details_client_name" id="project_details_client_name" value="<?php echo project_details_get_meta( 'project_details_client_name' ); ?>">
	</p>	<p>
		<label for="project_details_year"><?php _e( 'Year', 'project_details' ); ?></label><br>
		<input type="text" name="project_details_year" id="project_details_year" value="<?php echo project_details_get_meta( 'project_details_year' ); ?>">
	</p>	<p>
		<label for="project_details_url"><?php _e( 'URL', 'project_details' ); ?></label><br>
		<input type="text" name="project_details_url" id="project_details_url" value="<?php echo project_details_get_meta( 'project_details_url' ); ?>">
	</p><?php
}

function project_details_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['project_details_nonce'] ) || ! wp_verify_nonce( $_POST['project_details_nonce'], '_project_details_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['project_details_client_name'] ) )
		update_post_meta( $post_id, 'project_details_client_name', esc_attr( $_POST['project_details_client_name'] ) );
	if ( isset( $_POST['project_details_year'] ) )
		update_post_meta( $post_id, 'project_details_year', esc_attr( $_POST['project_details_year'] ) );
	if ( isset( $_POST['project_details_url'] ) )
		update_post_meta( $post_id, 'project_details_url', esc_attr( $_POST['project_details_url'] ) );
}
add_action( 'save_post', 'project_details_save' );

/*
	Usage: project_details_get_meta( 'project_details_client_name' )
	Usage: project_details_get_meta( 'project_details_year' )
	Usage: project_details_get_meta( 'project_details_url' )
	
*/
