<?php
/**
 * corporate-munk Team Post Type
 *
 * @package business-munk
 */

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function job_title_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function job_title_add_meta_box() {
	add_meta_box(
		'job_title-job-title',
		__( 'Job Title', 'job_title' ),
		'job_title_html',
		'mu_team',
		'normal',
		'high'
	);
}
add_action( 'add_meta_boxes', 'job_title_add_meta_box' );

function job_title_html( $post) {
	wp_nonce_field( '_job_title_nonce', 'job_title_nonce' ); ?>

	<p>
		<label for="job_title_enter_job_title_here"><?php _e( 'Enter Job Title Here', 'job_title' ); ?></label><br>
		<input type="text" name="job_title_enter_job_title_here" id="job_title_enter_job_title_here" value="<?php echo job_title_get_meta( 'job_title_enter_job_title_here' ); ?>">
	</p><?php
}

function job_title_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['job_title_nonce'] ) || ! wp_verify_nonce( $_POST['job_title_nonce'], '_job_title_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['job_title_enter_job_title_here'] ) )
		update_post_meta( $post_id, 'job_title_enter_job_title_here', esc_attr( $_POST['job_title_enter_job_title_here'] ) );
}
add_action( 'save_post', 'job_title_save' );

/*
	Usage: job_title_get_meta( 'job_title_enter_job_title_here' )
*/
